Adding dependency `anaconda/2020.11:python3` to your environment
Adding package `my_py_env/20221129` to your environment
/home/2688/.conda/my_py_env/20221129/lib/python3.10/site-packages/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: CD2
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/2688/.conda/my_py_env/20221129/lib/python3.10/site-packages/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: CE1
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/2688/.conda/my_py_env/20221129/lib/python3.10/site-packages/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: CG
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/2688/.conda/my_py_env/20221129/lib/python3.10/site-packages/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: HD1
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/2688/.conda/my_py_env/20221129/lib/python3.10/site-packages/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: HD2
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/2688/.conda/my_py_env/20221129/lib/python3.10/site-packages/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: HE1
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/2688/.conda/my_py_env/20221129/lib/python3.10/site-packages/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: HE2
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/2688/.conda/my_py_env/20221129/lib/python3.10/site-packages/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: HG
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/2688/.conda/my_py_env/20221129/lib/python3.10/site-packages/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: ND1
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/2688/.conda/my_py_env/20221129/lib/python3.10/site-packages/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: NE2
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/2688/.conda/my_py_env/20221129/lib/python3.10/site-packages/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: HW1
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/2688/.conda/my_py_env/20221129/lib/python3.10/site-packages/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: HW2
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/2688/.conda/my_py_env/20221129/lib/python3.10/site-packages/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: OW
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
slurmstepd: error: *** JOB 3976172 ON r1n39 CANCELLED AT 2023-03-27T19:02:52 ***
